#!/usr/bin/perl

use DBI;
use strict;

use Getopt::GUI::Long;
Getopt::GUI::Long::Configure(qw(display_help no_ignore_case capture_output));

my %opts = ('d' => 'FCC-data',
            'D' => 'simplexmap');
my $sth;

GetOptions(\%opts,
	   ["c|create-dbs", "Drop and recreate the tables"],
	   ["D|db=s","DB Name (defaults to 'simplexmap')"],
       ["U|db-user=s", "DB User"],
       ["P|db-pass=s", "DB Password"],
	   ["nogui", "Don't launch using a gui"],
	  ) || die;

if (!exists($opts{'U'}) ||
    !exists($opts{'P'})) {
    print STDERR "-U and -P are required\n";
    exit 1;
}

#my $dbh = DBI->connect("DBI:SQLite:dbname=$opts{D}");
my $dbh = DBI->connect("DBI:mysql:database=$opts{'D'};host=localhost", $opts{'U'}, $opts{'P'});

if ($opts{'c'}) {
	foreach my $table (qw(connections eventmembers events groups locations members people)) {
		$dbh->do("drop table " . $table);
	}
}



    $dbh->do("create table people
(
      id                        int,
      callsign                  varchar(10),
      firstname                 varchar(64),
      lastname                  varchar(64),
      salt                      varchar(64),
      password                  varchar(128),
      email                     varchar(255),
      validation                varchar(64),
      admin                     char(1)
)");

    $dbh->do("create table groups
(
      id                        int,
      name                      varchar(64),
      password                  varchar(64),
      adminpass                 varchar(64)
)");

    $dbh->do("create table members
(
      groupid                   int,
      groupperson               int
)");

    $dbh->do("create table events
(
      eventid                   int,
      eventgroup                int,
      eventname                 varchar(64),
      eventband                 varchar(64),
      eventdate                 varchar(64),
      eventstart                varchar(64),
      eventdescription          varchar(4096)
)");

    $dbh->do("create table locations
(
      locationid          int,
      locationperson      int,
      locationname        varchar(64),
      locationtype        varchar(64),
      locationlat         varchar(4096),
      locationlon         varchar(4096),
      locationaddress     varchar(4096),
      locationcity        varchar(4096),
      locationstate       varchar(4096),
      locationzip         int
)");

    $dbh->do("create table eventmembers
(
      eventid                   int,
      eventperson               int,
      eventpersonlocation       int,
      eventpersondetails        varchar(4096)
)");

    $dbh->do("create table connections
(
      eventid                   int,
      listener                  int,
      heard                     int,
      comment                   varchar(255),
      rating                    int
)");
