#!/usr/bin/perl

use DBI;
use strict;

use Getopt::GUI::Long;
Getopt::GUI::Long::Configure(qw(display_help no_ignore_case capture_output));

my %opts = ('d' => 'FCC-data',
	    'D' => 'hammap');
my $sth;

GetOptions(\%opts,
	   ["c|create-dbs", "Drop and recreate the tables"],
	   ["D|db","DB File"],
	   ["nogui", "Don't launch using a gui"],
	  ) || die;

if ($opts{'c'}) {
    unlink($opts{D});
}

my $dbh = DBI->connect("DBI:SQLite2:dbname=$opts{D}");

    $dbh->do("create table people
(
      id                        int,
      callsign                  char(10)
)");

    $dbh->do("insert into people values(1,'KI6NQW')");

    $dbh->do("create table groups
(
      id                        int,
      name                      char(64),
      password                  char(64),
      adminpass                 char(64)
)");

    $dbh->do("insert into groups values(1,'Yolo ARES','generalpassword','adminpassword')");

    $dbh->do("create table members
(
      groupid                   int,
      groupperson               int
)");

    $dbh->do("create table events
(
      eventid                   int,
      eventgroup                int,
      eventname                 varchar(64),
      eventband                 varchar(64),
      eventdate                 varchar(64),
      eventstart                varchar(64),
      eventdescription          varchar(4096)
)");

$dbh->do("insert into events values(1,1,'Test Net','2M','2008/03/02','7:30PM', '')");

    $dbh->do("create table eventmembers
(
      eventid                   int,
      eventperson               int,
      eventpersondetails        varchar(4096),
      eventpersonlocname        varchar(64),
      eventpersonloctype        varchar(64),
      eventpersonloclat         varchar(4096),
      eventpersonloclon         varchar(4096),
      eventpersonlocaddress     varchar(4096),
      eventpersonloccity        varchar(4096),
      eventpersonlocstate       varchar(4096),
      eventpersonloczip         int
)");

    $dbh->do("create table connections
(
      eventid                   int,
      listener                  int,
      heard                     int,
      comment                   char(10),
      rating                    int
)");
