#!/usr/bin/perl

use DBI;
use strict;

use Getopt::GUI::Long;
Getopt::GUI::Long::Configure(qw(display_help no_ignore_case capture_output));

my %opts = ('d' => 'FCC-data',
            'D' => 'simplexmap');
my $sth;

GetOptions(\%opts,
	   ["c|create-dbs", "Drop and recreate the tables"],
	   ["D|db=s","DB Name (defaults to 'simplexmap')"],
       ["U|db-user=s", "DB User"],
       ["P|db-pass=s", "DB Password"],
	   ["nogui", "Don't launch using a gui"],
	  ) || die;

if (!exists($opts{'U'}) ||
    !exists($opts{'P'})) {
    print STDERR "-U and -P are required\n";
    exit 1;
}

#my $dbh = DBI->connect("DBI:SQLite:dbname=$opts{D}");
my $dbh = DBI->connect("DBI:mysql:database=$opts{'D'};host=localhost", $opts{'U'}, $opts{'P'});

if ($opts{'c'}) {
	foreach my $table (qw(connections eventmembers events groups locations members people)) {
		$dbh->do("drop table " . $table);
	}
}



    $dbh->do("create table people
(
      id                        int(11) NOT NULL auto_increment primary key,
      callsign                  varchar(10),
      firstname                 varchar(64),
      lastname                  varchar(64),
      salt                      varchar(64),
      password                  varchar(128),
      email                     varchar(255),
      validation                varchar(64),
      admin                     char(1)
)");

    $dbh->do("create table groups
(
      id                        int(11) NOT NULL auto_increment primary key,
      name                      varchar(64),
      password                  varchar(64),
      adminpass                 varchar(64)
)");

    $dbh->do("create table members
(
      groupid                   int,
      groupperson               int
)");

    $dbh->do("create table events
(
      eventid                   int(11) NOT NULL auto_increment primary key,
      eventgroup                int,
      eventname                 varchar(64),
      eventband                 varchar(64),
      eventdate                 varchar(64),
      eventstart                varchar(64),
      eventdescription          varchar(4096)
)");

$dbh->do("create table symbols
(
      symbolid            int(11) NOT NULL auto_increment primary key,
      symbolname          varchar(64),
      symboldescription   varchar(4096),
      symbolicon          varchar(256),
      symboliconsize      int default 24
)");

    $dbh->do("create table locations
(
      locationid          int(11) NOT NULL auto_increment primary key,
      locationperson      int,
      locationname        varchar(64),
      locationanttenna     varchar(4096),
      locationtransmiter  varchar(4096),
      locationprivacy     CHAR,			
      locationtype        varchar(64),
      locationlat         varchar(4096),
      locationlon         varchar(4096),
      locationaddress     varchar(4096),
      locationcity        varchar(4096),
      locationstate       varchar(4096),
      locationzip         int,
      locationsymbol      int default 1
)");

# privacy values:
#   M: mine only
#   F: friends
#   G: friends and groups
#   P: public

# alter table locations add column locationantenna     varchar(4096);
# alter table locations add column locationtransmiter  varchar(4096);
# alter table locations add column locationprivacy     CHAR;
# update locations set locationprivacy = 'P'; 



$dbh->do("create table repeaters(
      repeaterid          int(11) NOT NULL auto_increment primary key,
      repeaterowner       int,
      repeatercallsign    varchar(16),
      repeatername        varchar(128),
      repeaternotes       varchar(4096),
      repeaterlat         varchar(4096),
      repeaterlon         varchar(4096),
      repeaterfreq        varchar(128),
      repeateroffset      CHAR,
      repeaterpl          varchar(32),
      repeaterdcs         varchar(32),
      repeaterpublic      CHAR,
                                )");

$dbh->do("create table repeaterlinks(
                                     fromid   int,
                                     toid     int,
                                     always   char default 'N'
                                     )");

# alter table repeaters add column repeatername        varchar(128);
# alter table repeaters add column   repeaterfreq        varchar(128);
# alter table repeaters add column   repeateroffset      CHAR;
# alter table repeaters add column   repeaterpl          varchar(32);
# alter table repeaters add column   repeaterdcs         varchar(32);
# alter table repeaters add column   repeaterpublic      CHAR;
# update repeaters set repeatername = repeaternotes;
# update repeaters set repeaternotes = "";



    $dbh->do("create table eventmembers
(
      eventid                   int,
      eventperson               int,
      eventpersonlocation       int,
      eventpersondetails        varchar(4096)
)");

    $dbh->do("create table connections
(
      eventid                   int,
      listener                  int,
      heard                     int,
      comment                   varchar(255),
      rating                    int,
      timelogged                int
)");

$dbh->do("create table repeatersignals
(
      repeaterid                int,
      listeningStation          int,
      repeaterStrength          int,
      sendingStrength           int
)");

$dbh->do("create table simplexsignals
(
      receiverid                int,
      transmitterid             int,
      signallevel               int
)");

