#!/usr/bin/perl

use GraphViz;
use DBI;
use strict;
use GeoDB::Utils;
use Geo::Coder::US;
use lib qw(/home/hardaker/lib/simplexmap);
use SimplexMap;

use Getopt::GUI::Long;
Getopt::GUI::Long::Configure(qw(display_help no_ignore_case capture_output));

my %opts = ('d' => 'hammap',
	    'b' => '2M',
	    'l' => 'dot',
#	    'o' => 'simplexmap.png',
	    'e' => .1,
	    'g' => '/home/hardaker/lib/simplexmap/tiger/mydb',
	    'H' => '/home/hambot/hamsigns');
my $sth;

GetOptions(\%opts,
	   ["d|db-file=s", "The database file"],
	   ["b|band=s", "Band to generate a map for"],
	   ["l|layout=s", "Layout style (dot, neato, twopi, circo, fdp)"],
	   ["e|epislon=s", "Epsilon value"],
	   ["o|output=s", "Output PNG File"],
	   ["k|output-kml=s", "Output KML file"],
	   ["c|output-csv=s", "Output CSV file"],
	   ["g|geodb=s", "Geographical tiger DB"],
	   ["H|hamsigns=s", "HAM Signs database"],
	   ["nogui", "Don't launch using a gui"],
	  ) || die;

init_simplexmap(\%opts);
print "kml count: " . export_kml($opts{'k'}) . "\n" if ($opts{'k'});
print "graphviz count: " . export_graphviz($opts{'o'}) . "\n" if ($opts{'o'});
print "CSV count: " . export_csv($opts{'c'}) . "\n" if ($opts{'c'});
