WS6Z's Simplex Mapping System

* Repeater and Simplex Mapping Tool

This software is designed to map repeater and simplex nets, allowing
users to graphically repent on a map who can talk to who/what.  This
may be highly useful for passing messages between stations.

At the moment, only the 2 meter frequency is really represented.

There is a public installation of the system available at:

  http://map.ws6z.com/

There, accounts can be created, repeaters can be listed, and signals
logged.

This version was completely rewritten from what is documented below
and uses the leaflet mapping code to render the maps in a much more
pleasant and interactive way.  The web interface also is significantly
improved, graphically, via the use of twitter's bootstrap css/js.

* EVERYTHING BELOW IS OUT OF DATE

* Project Details

  http://simplexmap.hamtools.org/docs/

  Note that this isn't the easiest set of software to get up and
  running, and these instructions aren't 100% complete.  But it's
  getting easier and the instructions are getting better.

  I'll grant anyone who needs it a group account on the [[http://simplexmap.hamtools.org/][public server]]
  if you'd rather do that than install the software on your own server.
  [I recommend you start with using the public one at least]

* Required Software

*** Perl Modules

    + Getopt::GUI::Long (it's possible to make this optional; let me know)
    + DBI
    + DBD::SQLite
    + Geo::Coder::US
    + GeoDB::Utils (Get it from geoqo.org)
    + GraphViz
    + IO::String
    + [[http://search.cpan.org/~hardaker/Ham-Callsign-0.31/][Ham::Callsign]]

*** Software

    + ImageMagick
    + graphviz

* Creating the initial database

  To create the initial database, which is stored in an SQLite file,
  run the createdb script:

    ./createdb -d mydb -u WS6Z -g mygroup -p sharedpassword -P myadminpassword

  This will create the 'mydb' file and populate it with the minimal
  required data: a single user (WS6Z) and a single group (mygroup)
  with both a shared password and a administrative password for the
  group.  Obviously you should change the passwords to something
  specific to you.  And it's unlikely you'll want to use my callsign :-)

* Installing the cgi-script that drives it all

  + modify the simplexmap program to point to your data.
    Specifically, in $opts:

    + set the 'd' option to the full path file for your database created above
    + set the 'H' option to the FCC callsign database created with 'cs'
      (you can grab a copy from [[http://www.hamtools.org/dbs/hamsigns]])
      (size: 526M)
    + set the 'g' option to the tiger db file
      (you can grab it from [[http://simplexmap.hamtools.org/geocoder.db]])
      (size: 884M)

  + cp simplexmap /your/cgi-bin

*** Creating your own Tiger DB file

    XXX

*** Creating your own FCC database file

    XXX

* Contacting the author

  Wes Hardaker < wes & ws6z.com >
